require "user.options"
require "user.keymaps"
require "user.plugins"

require "user.lsp"

require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.feline"
require "user.gitsigns"
require "user.impatient"
require "user.indent-blankline"
require "user.nvim-gps"
require "user.nvim-tree"
require "user.project"
require "user.stabilize"
require "user.telescope"
require "user.toggle_term"
require "user.treesitter"
require "user.which-key"
