require("user.options")
require("user.keymaps")
require("user.plugins")

require("user.lsp")

require("user.autopairs")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
-- require("user.feline")
require("user.lualine")
require("user.gitsigns")
require("user.impatient")
require("user.indent-blankline")
require("user.nvim_dap")
require("user.nvim_dap_install")
require("user.nvim-gps")
require("user.nvim-tree")
require("user.package_info")
require("user.project")
require("user.stabilize")
require("user.telescope")
require("user.toggle_term")
require("user.treesitter")
require("user.which-key")
